version: '3.8'

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: npm run start:debug
        ports:
            - 8080:8080
            - 5555:5555
        networks:
            - easy-whatsapp
        volumes:
            - ./sessions:/app/sessions
        env_file:
            - backend.env
        restart: unless-stopped
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        command: npm run start
        ports:
            - 3000:3000
        networks:
            - easy-whatsapp
        env_file:
            - frontend.env
        restart: unless-stopped
        depends_on:
            - backend

networks:
    easy-whatsapp: